#!/usr/bin/env python3
import json
from pathlib import Path

def convert_md_to_js():
    project_dir = Path(__file__).parent.parent
    
    # 1. 부록 평가 마크다운 변환 (기존 성취도 -> 부록 테스트)
    appendix_md_dir = project_dir / "appendix_test" / "md"
    appendix_output = project_dir / "src" / "data" / "appendixTestData.js"
    
    if appendix_md_dir.exists():
        appendix_data = {}
        md_files = sorted(list(appendix_md_dir.glob("*.md")))
        for md_file in md_files:
            content = md_file.read_text(encoding="utf-8")
            appendix_data[md_file.stem] = content
            print(f"Loaded appendix: {md_file.name} ({len(content)} chars)")
            
        appendix_output.parent.mkdir(parents=True, exist_ok=True)
        js_content = [
            "// Automatically generated by convert_appendix.py. Do not edit directly.",
            f"export const appendixTestData = {json.dumps(appendix_data, ensure_ascii=False, indent=2)};",
            ""
        ]
        appendix_output.write_text("\n".join(js_content), encoding="utf-8")
        print(f"🎉 Success: Created appendixTestData.js with {len(appendix_data)} exams.")
    else:
        print(f"Warning: Appendix directory {appendix_md_dir} does not exist.")

    # 1.5. 신규 정기 성취도 평가 마크다운 변환 (신규 achievement_test -> achievementTestData.js)
    achievement_md_dir = project_dir / "achievement_test" / "md"
    achievement_output = project_dir / "src" / "data" / "achievementTestData.js"
    
    if achievement_md_dir.exists():
        achievement_data = {}
        md_files = sorted(list(achievement_md_dir.glob("*.md")))
        for md_file in md_files:
            content = md_file.read_text(encoding="utf-8")
            achievement_data[md_file.stem] = content
            print(f"Loaded achievement: {md_file.name} ({len(content)} chars)")
            
        achievement_output.parent.mkdir(parents=True, exist_ok=True)
        js_content = [
            "// Automatically generated by convert_appendix.py. Do not edit directly.",
            f"export const achievementTestData = {json.dumps(achievement_data, ensure_ascii=False, indent=2)};",
            ""
        ]
        achievement_output.write_text("\n".join(js_content), encoding="utf-8")
        print(f"🎉 Success: Created achievementTestData.js with {len(achievement_data)} exams.")
    else:
        print(f"Warning: Achievement directory {achievement_md_dir} does not exist.")

    # 2. 레벨테스트 마크다운 변환
    resource_dir = project_dir / "level_test"
    level_output = project_dir / "src" / "data" / "levelTestData.js"
    
    level_files = [
        "elementary_test.md",
        "middle_basic.md",
        "middle_intermediate.md",
        "middle_advanced.md",
        "middle_grammar.md",
        "high_level_1.md",
        "high_level_2.md"
    ]
    
    if resource_dir.exists():
        level_data = {}
        for filename in level_files:
            file_path = resource_dir / filename
            if file_path.exists():
                content = file_path.read_text(encoding="utf-8")
                key = file_path.stem
                level_data[key] = content
                print(f"Loaded level test: {filename} ({len(content)} chars)")
            else:
                print(f"Warning: Level test file {file_path} not found.")
                
        level_output.parent.mkdir(parents=True, exist_ok=True)
        js_content = [
            "// Automatically generated by convert_appendix.py. Do not edit directly.",
            f"export const levelTestData = {json.dumps(level_data, ensure_ascii=False, indent=2)};",
            ""
        ]
        level_output.write_text("\n".join(js_content), encoding="utf-8")
        print(f"🎉 Success: Created levelTestData.js with {len(level_data)} exams.")
    else:
        print(f"Error: Resource directory {resource_dir} does not exist.")

if __name__ == "__main__":
    convert_md_to_js()
